export const OPS = [
  { v: "==",           l: "equals" },
  { v: "!=",           l: "not equals" },
  { v: ">",            l: ">" },
  { v: ">=",           l: ">=" },
  { v: "<",            l: "<" },
  { v: "<=",           l: "<=" },
  { v: "contains",     l: "contains" },
  { v: "starts_with",  l: "starts with" },
  { v: "ends_with",    l: "ends with" },
  { v: "is_empty",     l: "is empty" },
  { v: "is_not_empty", l: "is not empty" },
];

export const FUNCTIONS = [
  { name: "SUMIFS",   args: 3,  hint: "SUMIFS(Amount, Region, RegionLookup)" },
  { name: "COUNTIFS", args: 3,  hint: "COUNTIFS(OrderID, Region, RegionLookup)" },
  { name: "AVGIFS",   args: 3,  hint: "AVGIFS(Price, Category, CategoryLookup)" },
  { name: "SUM",      args: 1,  hint: "SUM(Sales)" },
  { name: "AVG",      args: 1,  hint: "AVG(Score)" },
  { name: "MIN",      args: 1,  hint: "MIN(Temperature)" },
  { name: "MAX",      args: 1,  hint: "MAX(Revenue)" },
  { name: "COUNT",    args: 1,  hint: "COUNT(Customer)" },
  { name: "STD",      args: 1,  hint: "STD(Returns)" },
  { name: "VAR",      args: 1,  hint: "VAR(Returns)" },
  { name: "ROWSUM",   args: -1, hint: "ROWSUM(Q1, Q2, Q3, Q4)" },
  { name: "ROWAVG",   args: -1, hint: "ROWAVG(Math, Science, English)" },
  { name: "ROWMIN",   args: -1, hint: "ROWMIN(PriceA, PriceB, PriceC)" },
  { name: "ROWMAX",   args: -1, hint: "ROWMAX(Score1, Score2, Score3)" },
  { name: "ADD",      args: 2,  hint: "ADD(Price, Tax)" },
  { name: "SUB",      args: 2,  hint: "SUB(Revenue, Cost)" },
  { name: "MUL",      args: 2,  hint: "MUL(Quantity, UnitPrice)" },
  { name: "DIV",      args: 2,  hint: "DIV(Total, Count)" },
];